// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templa

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Hello(name string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"description\" content=\"Tutorme Signup Page\"><title>Tutorme - Login</title><!-- Link to external stylesheets --><script src=\"https://unpkg.com/htmx.org@2.0.2\" integrity=\"sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ\" crossorigin=\"anonymous\"></script><!-- Favicon --><link rel=\"icon\" href=\"favicon.ico\" type=\"image/x-icon\"></head><body><h3>Signup Form</h3><form hx-post=\"/create-account\"><div hx-target=\"this\" hx-swap=\"outerHTML\"><label>Email Address</label> <input name=\"email\" hx-indicator=\"#ind\"></div><div class=\"form-group\"><label>Name</label> <input type=\"text\" class=\"form-control\" name=\"name\"></div><div class=\"form-group\"><label>Grade Level</label> <input type=\"number\" class=\"form-control\" name=\"grade_level\"></div><div class=\"form-group\"><label>Role</label> <input type=\"text\" class=\"form-control\" name=\"role\"></div><div class=\"form-group\"><label>Gender</label> <input type=\"text\" class=\"form-control\" name=\"gender\"></div><div class=\"form-group\"><label>Subject</label> <input type=\"text\" class=\"form-control\" name=\"subject\"></div><button hx-post=\"/create-account\" hx-trigger=\"click\" hx-swap=\"outerHTML\">Click Me!</button></form></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
