// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tutor struct {
	UserID     pgtype.UUID
	Name       string
	GradeLevel int32
	Role       string
	Gender     string
	Subject    string
}
