// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
)

const createTutor = `-- name: CreateTutor :one
INSERT INTO tutors (
  user_id, name, grade_level, role, gender, subject
) VALUES (
  gen_random_uuid(), $1, $2, $3, $4, $5
)
RETURNING user_id, name, email, grade_level, role, gender, subject
`

type CreateTutorParams struct {
	Name       string
	GradeLevel int32
	Role       string
	Gender     string
	Subject    string
}

func (q *Queries) CreateTutor(ctx context.Context, arg CreateTutorParams) (Tutor, error) {
	row := q.db.QueryRow(ctx, createTutor,
		arg.Name,
		arg.GradeLevel,
		arg.Role,
		arg.Gender,
		arg.Subject,
	)
	var i Tutor
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.GradeLevel,
		&i.Role,
		&i.Gender,
		&i.Subject,
	)
	return i, err
}
