// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
)

const createTutor = `-- name: CreateTutor :one
INSERT INTO tutors (
  user_id, name, grade_level, role, gender, subject
) VALUES (
  gen_random_uuid(), $1, $2, $3, $4, $5
)
RETURNING user_id, name, grade_level, role, gender, subject
`

type TutorParams struct {
  Name       string `json:"name"`
	GradeLevel int32  `json:"grade_level"`
	Role       string `json:"role"`
	Gender     string `json:"gender"`
	Subject    string `json:"subject"`
}

func (q *Queries) CreateTutor(ctx context.Context, arg TutorParams) (Tutor, error) {
	row := q.db.QueryRow(ctx, createTutor,
		arg.Name,
		arg.GradeLevel,
		arg.Role,

		arg.Gender,
		arg.Subject,
	)
	var i Tutor
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.GradeLevel,
		&i.Role,
		&i.Gender,
		&i.Subject,
	)
	return i, err
}
